### ISSUE TITLE
The unit of your auto trajectory

### ISSUE THREAD

**Issue by mendax1234** [FRCTeam2910/2021CompetitionRobot#1]
My team will use swerve in this season and after watching your team's excellect performance in the chezt champs , we would like to use your lib in the auto. However , l am having some questions about your trajectory. 
First, what 's the unit of each waypoint?
<img width="523" alt="image" src="https://user-images.githubusercontent.com/62934294/151516420-0dc34ea9-27c6-4329-a0f1-9f7bc7428ca5.png">

Any reply is appreciated!

**Comment by Unknown-Lego** [comment]
It is in centimeters.

**Comment by mendax1234** [comment]
Thanks！

**Comment by JacobJBublitz** [comment]
@Unknown-Lego that's actually incorrect. The units are in inches.

**Comment by Unknown-Lego** [comment]
so does that mean Jacob let a non-metic unit be allowed?
